### PR TITLE
upgrade debug to 2.6.9

### PR DESCRIPTION
**Pull request by rcarroll380**
https://nodesecurity.io/advisories/534

### CODE REVIEW

**Comment by rcarroll380** [comment]
Addresses https://github.com/agebrock/tunnel-ssh/issues/57

**Comment by MarcosRava** [comment]
Do you have any prediction to this PR?

Tks

**Comment by rcarroll380** [comment]
@agebrock anything we can do to get this merged and a new version released?

**Comment by heikkipora** [comment]
@agebrock please could you take the time to merge this PR and release a new version of ```tunnel-ssh``` with it? ```tunnel-ssh``` is now flagged as being vulnerable (and for a reason).

**Comment by ceastman-ibm** [comment]
@agebrock Would you have time to merge this PR? This is getting flagged as being vulnerable now: https://snyk.io/vuln/npm:debug:20170905

**Comment by agebrock** [comment]
Sorry guys i am traveling around asia right now and lagging a bit behind. Commit is merged and packages are updated and pushed to npm .

**Comment by heikkipora** [comment]
Thank you @agebrock, this is super helpful! Safe travels!

**Comment by evansantos** [comment]
You rock guys ✌️

**Pull request merged**
